sudo: required
services:
  - docker
language: bash
env:
  - TYPE=cli
  - TYPE=fpm
script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build image
  - ./build.sh $TYPE
  # test image
  - ./test.sh $TYPE
  # push image
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      ./push.sh $TYPE
    fi